name = "redzone-nfl-api"
main = "src/index.ts"
compatibility_date = "2025-04-01"

[[d1_databases]]
binding = "DB"
database_name = "redzone-db"
database_id = "8047c370-a9b5-4cd2-bb19-e8dc870cf744"

[vars]
THE_SPORTS_DB_API_KEY = ""
